language: node_js
matrix:
  include:
    - node_js: "0.12"
    - node_js: "4.0"
    - node_js: "5.0"
    - node_js: "6.0"
    - node_js: "node"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
script:
  - npm test